"""Shared data models for SolverV8."""

from dataclasses import dataclass


_COHERENCE_CHANGE = {"Ku": 1, "Kd": -1, "Bu": -1, "Bd": 1}


def _coherence_orders_from_interactions(interactions):
    """Return the signed coherence history implied by UFSS interactions."""
    current = 0
    orders = []
    for interaction in interactions:
        current += _COHERENCE_CHANGE[interaction]
        orders.append(current)
    return tuple(orders)


def _response_prefactor_from_interactions(interactions, amplitude=1.0):
    """Return the perturbative prefactor for an ordered Liouville pathway."""
    bra_sign = -1 if sum(item.startswith("B") for item in interactions) % 2 else 1
    return complex(amplitude) * (1j ** len(interactions)) * bra_sign


@dataclass(frozen=True)
class FrequencyPathway:
    """
    Frequency-domain representation of one UFSS density-matrix diagram.

    Parameters
    ----------
    name : str
        Public pathway label, for example ``R1``.
    interactions : tuple of str
        Ordered UFSS interaction labels (Ku, Kd, Bu, Bd).
    pulse_indices : tuple of int
        UFSS pulse index associated with each interaction.
    component : str
        Spectrum group, normally ``"rephasing"`` or ``"unrephasing"``.
    amplitude : complex
        Additional user-supplied pathway amplitude. The bra-side commutator
        sign is applied automatically for legacy third-order pathways.
    prefactor : complex or None
        Complete response prefactor. It is required outside third order.
    coherence_orders : tuple of int
        Signed coherence order after each interaction. When supplied, the
        complete history must match the interaction-implied history exactly.
    """

    name: str
    interactions: tuple
    pulse_indices: tuple = ()
    component: str = "custom"
    amplitude: complex = 1.0
    prefactor: complex = None
    coherence_orders: tuple = ()

    def __post_init__(self):
        interactions = tuple(str(item) for item in self.interactions)
        pulse_indices = tuple(int(item) for item in self.pulse_indices)
        coherence_orders = tuple(int(item) for item in self.coherence_orders)
        component = str(self.component).lower().replace("-", "")
        if component in {"nonrephasing", "nonrephase"}:
            component = "unrephasing"
        valid = {"Ku", "Kd", "Bu", "Bd"}
        unknown = [item for item in interactions if item not in valid]
        if unknown:
            raise ValueError(
                f"Unknown UFSS interaction label(s): {unknown}. "
                "Expected Ku, Kd, Bu, or Bd."
            )
        if pulse_indices and len(pulse_indices) != len(interactions):
            raise ValueError(
                "pulse_indices must be empty or have one entry per interaction."
            )
        if coherence_orders and len(coherence_orders) != len(interactions):
            raise ValueError(
                "coherence_orders must be empty or have one entry per interaction."
            )
        expected_coherence_orders = _coherence_orders_from_interactions(interactions)
        if coherence_orders and coherence_orders != expected_coherence_orders:
            mismatch_index = next(
                index
                for index, (declared, expected) in enumerate(
                    zip(coherence_orders, expected_coherence_orders), start=1
                )
                if declared != expected
            )
            raise ValueError(
                f"Signed coherence metadata mismatch after interaction "
                f"{mismatch_index} for pathway {self.name!r}: declared "
                f"q={coherence_orders[mismatch_index - 1]}, but interactions "
                f"imply q={expected_coherence_orders[mismatch_index - 1]}."
            )
        if self.prefactor is None and len(interactions) != 3:
            raise ValueError(
                "An explicit prefactor is required for pathways whose order "
                "is not three."
            )
        object.__setattr__(self, "interactions", interactions)
        object.__setattr__(self, "pulse_indices", pulse_indices)
        object.__setattr__(self, "coherence_orders", coherence_orders)
        object.__setattr__(self, "component", component)
        object.__setattr__(self, "amplitude", complex(self.amplitude))
        if self.prefactor is not None:
            object.__setattr__(self, "prefactor", complex(self.prefactor))

    @property
    def bra_sign(self):
        """Commutator sign generated by bra-side interactions."""
        return -1 if sum(item.startswith("B") for item in self.interactions) % 2 else 1

    @property
    def coefficient(self):
        """Total relative pathway coefficient, excluding the common ``-1j``."""
        return self.amplitude * self.bra_sign

    @property
    def ufss_diagram(self):
        """Return the ordered UFSS instructions represented by this pathway."""
        pulse_indices = (
            self.pulse_indices
            if self.pulse_indices
            else tuple(range(len(self.interactions)))
        )
        return tuple(zip(self.interactions, pulse_indices))

    def metadata(self):
        """Return serializable plotting and provenance metadata."""
        return {
            "name": self.name,
            "interactions": self.interactions,
            "pulse_indices": self.pulse_indices,
            "coherence_orders": self.coherence_orders,
            "component": self.component,
            "amplitude": self.amplitude,
            "prefactor": self.prefactor,
            "response_prefactor": self.response_prefactor,
            "ufss_diagram": self.ufss_diagram,
        }

    @property
    def response_prefactor(self):
        """Return the complete complex response prefactor."""
        if self.prefactor is not None:
            return self.prefactor
        return -1j * self.coefficient


@dataclass(frozen=True)
class PropagationInterval:
    """One propagation interval following a light-matter interaction."""

    name: str
    domain: str
    coherence_order: int = None

    def __post_init__(self):
        domain = str(self.domain).lower()
        if domain not in {"frequency", "time", "identity"}:
            raise ValueError("domain must be 'frequency', 'time', or 'identity'.")
        name = str(self.name)
        if domain != "identity" and not name:
            raise ValueError("Frequency and time intervals require a name.")
        object.__setattr__(self, "name", name)
        object.__setattr__(self, "domain", domain)
        if self.coherence_order is not None:
            object.__setattr__(self, "coherence_order", int(self.coherence_order))


@dataclass(frozen=True)
class SpectroscopyProtocol:
    """Propagation topology used to evaluate a pathway."""

    intervals: tuple
    name: str = "custom"

    def __post_init__(self):
        intervals = tuple(
            item if isinstance(item, PropagationInterval)
            else PropagationInterval(**item)
            for item in self.intervals
        )
        if not intervals:
            raise ValueError("A protocol requires at least one interval.")
        names = [item.name for item in intervals if item.domain != "identity"]
        if len(names) != len(set(names)):
            raise ValueError("Non-identity interval names must be unique.")
        object.__setattr__(self, "intervals", intervals)
        object.__setattr__(self, "name", str(self.name))

    @property
    def frequency_axis_names(self):
        return tuple(
            item.name for item in self.intervals if item.domain == "frequency"
        )

    @property
    def time_interval_names(self):
        return tuple(item.name for item in self.intervals if item.domain == "time")

    def validate_pathway(self, pathway):
        if len(pathway.interactions) != len(self.intervals):
            raise ValueError(
                f"Protocol {self.name!r} has {len(self.intervals)} intervals, "
                f"but pathway {pathway.name!r} has "
                f"{len(pathway.interactions)} interactions."
            )
        if pathway.coherence_orders:
            for index, (expected, actual) in enumerate(
                zip(self.intervals, pathway.coherence_orders), start=1
            ):
                if (
                    expected.coherence_order is not None
                    and abs(actual) != abs(expected.coherence_order)
                ):
                    raise ValueError(
                        f"Coherence mismatch after interaction {index}: "
                        f"protocol expects |q|={abs(expected.coherence_order)}, "
                        f"pathway {pathway.name!r} has q={actual}."
                    )


@dataclass
class SpectrumResult:
    """Two-dimensional spectra and their axis/pathway metadata."""

    axis_names: tuple
    axis_values: tuple
    pathways: dict
    components: dict
    coherence_orders: dict
    fixed_coordinates: dict
    pathway_metadata: dict = None

    def __post_init__(self):
        if self.pathway_metadata is None:
            self.pathway_metadata = {}


@dataclass
class PathwayPlotResult:
    """Matplotlib and UFSS artifacts produced by a multi-order pathway plot."""

    figure: object
    axes: object
    panel_names: tuple
    diagrams: dict
    diagram_paths: dict
    spectrum_pdf: object = None


coherence_orders_from_interactions = _coherence_orders_from_interactions
response_prefactor_from_interactions = _response_prefactor_from_interactions
